// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"AI_Bridge","status":true,"description":"AI Bridge Plugin - 連接 RPG Maker MV 與 AI-Agent 系統","parameters":{}},
{"name":"AntiFraudGame","status":true,"description":"防詐騙教育遊戲插件 - 整合 AI-Agent 系統 (RPG Maker MV)","parameters":{}},
{"name":"AutoScamBattle","status":false,"description":"自动防诈骗战斗系统 - 完全自动化的对话战斗","parameters":{"API_URL":"http://localhost:8000"}},
{"name":"RotatingScamSystem","status":false,"description":"輪換詐騙系統 - 6個NPC輪流使用10種騙局","parameters":{"API_URL":"http://localhost:8000"}},
{"name":"SimulationTraining","status":false,"description":"防詐騙模擬訓練系統 - 使用 simulation_routes.py API","parameters":{"API_URL":"http://localhost:8000","WS_URL":"ws://localhost:8000","AUTO_RECONNECT":"true","SHOW_TRUST_UPDATES":"true","SHOW_PERFORMANCE_SCORES":"true","simulationVarId":"20"}},
{"name":"SimulationTraining_Compatible","status":true,"description":"防詐騙模擬訓練系統 - 完全兼容原有RotatingScamSystem設置","parameters":{"API_URL":"http://localhost:8000","AutoStartOnMap":"2","AutoStartSwitch":"0","AutoStartDelay":"3","AutoSelectNewGame":"true","NewGameDelay":"2","AutoTransferToTrainingMap":"true","TrainingMapId":"2","TrainingMapX":"5","TrainingMapY":"9","TransferDelay":"2","AutoSelectDialogue":"true","DialogueSelectionDelay":"1"}},
{"name":"SimulationTraining_WithNPC","status":false,"description":"防詐騙模擬訓練系統 - 帶NPC自動移動功能","parameters":{"API_URL":"http://localhost:8000","NPC_SPEED":"4","showSimulationDetails":"false","simulationVarId":"20"}},
{"name":"SimulationTraining_Simple","status":false,"description":"防詐騙訓練系統 - 簡化版（使用原生消息系統）","parameters":{"ApiUrl":"http://localhost:8000","AutoStartOnMap":"2","AutoStartSwitch":"10"}},
{"name":"SimulationTraining_SessionBased","status":false,"description":"防詐騙訓練系統 - Session/歷史記錄版本","parameters":{"ApiUrl":"http://localhost:8000","AutoStartOnMap":"2"}},
{"name":"VoiceInput","status":true,"description":"語音輸入插件 - 支持廣東話語音識別","parameters":{}}
];
